apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
<<<<<<< HEAD
=======
  namespace: argocd  # Or whatever namespace Argo CD runs in
  finalizers:
    - resources-finalizer.argocd.argoproj.io
>>>>>>> 91a61631dd6dadbd6ee0b74b7f08587017945b74
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 59.0.0  # Pick a stable version
    helm:
      values: |
        grafana:
          enabled: true
          persistence:
            enabled: true
            size: 2Gi
          adminPassword: "admin"
          service:
            type: ClusterIP
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        loki:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

